### ISSUE TITLE
Error on import 'stardust-webgl'

### ISSUE THREAD

**Issue by RMKD** [stardustjs/stardust-webgl#1]
`import * as StardustWebGL from "stardust-webgl";`

yields this error when trying to import in React: 

`Module not found: Can't resolve 'stardust-webgl' in '~/stardust-react/src'`

tested with the following dependencies in `package.json`:  

```
  "dependencies": {
    "d3": "^4.9.1",
    "fs": "^0.0.1-security",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "stardust-core": "^0.0.2",
    "stardust-webgl": "^0.0.2-a",
    "fbemitter": "^2.1.1",
    "flux": "^3.0.0",
    "typescript": "^2.0.10",
    "typings": "^2.0.0"
  }
```

both `stardust-core` and `stardust-webgl` are present in `~/stardust-react/node_modules/`

**Comment by RMKD** [comment]
it turns out `stardust-webgl` also fails on https://npm.runkit.com/stardust-webgl so it appears there is an issue with the published package

<img width="580" alt="npm-runkit-error" src="https://user-images.githubusercontent.com/334410/27510069-9d298ab8-58d7-11e7-8985-b6da31eb35b2.png">

**Comment by donghaoren** [comment]
thank you for reporting this issue! it's because the `files` entry in `package.json` was missing so that the `dist` folder wasn't submitted to the npm module.
